name: "Publish"

on:
  push:
    branches:
      - "launcher"
    paths-ignore:
      - "README.md"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    permissions: write-all
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '23'
          java-package: jdk+fx
          cache: gradle

      - name: Install packaging tools (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y rpm fakeroot

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Build Packages
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./gradlew packageMsi
            ./gradlew packageExe
            ./gradlew zipPackage
          elif [ "$RUNNER_OS" == "Linux" ]; then
            ./gradlew packageDeb
            ./gradlew packageRpm
            ./gradlew zipPackage
          elif [ "$RUNNER_OS" == "macOS" ]; then
            ./gradlew packageDmg
            ./gradlew packagePkg
            ./gradlew zipPackage
          fi
          ./gradlew generateChecksums
        shell: bash

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: build/dist/*

  release:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: Prepare Release Files
        run: |
          mkdir -p release-dist
          # On cherche tous les fichiers binaires et checksums récursivement pour les mettre à plat
          find all-artifacts -type f \( -name "*.exe" -o -name "*.msi" -o -name "*.deb" -o -name "*.rpm" -o -name "*.dmg" -o -name "*.pkg" -o -name "*.zip" -o -name "*.jar" -o -name "*.sha256" \) -exec cp {} release-dist/ \;

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release v${{ github.run_number }}"
          files: release-dist/*